// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "warscroll_collector.h"

std::string warscroll_collector::echo(const std::string& text)
{
    return "Hi, " + text;
}

