// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "calculator.h"

std::string calculator::echo(const std::string& text)
{
    return "Hi, " + text;
}

