include_directories("${gtest_SOURCE_DIR}/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/googletest-src/googletest/include")

include_directories("${CMAKE_CURRENT_BINARY_DIR}/libxml2-src/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/libxml2-build")
link_directories("${CMAKE_CURRENT_BINARY_DIR}/libxml2-build")

link_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-build/lib")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-src/util/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-src/framework/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-src/shellservice/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-src/third_party/benchmark/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-src/webconsole/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-src/compendium/ServiceComponent/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-src/compendium/test_bundles/IDictionaryService/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-src/compendium/test_bundles/ISpellCheckService/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-src/compendium/test_bundles/TestInterfaces/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-src/compendium/CM/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-src/compendium/LogService/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-src/httpservice/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-build/include")
include_directories("${CMAKE_CURRENT_BINARY_DIR}/cppmicroservices-build/framework/include")
